# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2 
jobs: 
  build: 
    machine: 
      docker_layer_caching: true 
      steps: 
        - checkout 
        - run: 
            name: build image 
            command: |
          docker build -t circleci-beanstalk-example . 
        - run: 
            name: Install awscli 
            command: |
              sudo apt-get update && sudo apt-get upgrade 
              sudo apt-get install python-dev && sudo apt-get upgrade 
              sudo pip install awsebcli --upgrade 
        - run: 
            name: Create AWS credentials manually 
            command: |
              mkdir ~/.aws 
              touch ~/.aws/config 
              chmod 600 ~/.aws/config 
              echo "[profile eb-cli]" > ~/.aws/config 
              echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config 
              echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config 
              echo "aws_region=$AWS_REGION" >> ~/.aws/config 
        - run: 
            name: Deploy to EB if branch is Master 
            command: |
               eb use jumaapp-dev --profile eb-cli
               eb deploy $jumaapp-dev-jumaapp --profile eb-cli

             
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master
                - develop




